package mailru;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

public class WriteMessage {
	
	private final static String EMAIL = " sviatlana.zakharenka@gmail.com";
	private final static String TOPIC = " Selenium Web Driver Test Message";


	
	private WebDriver driver;

	public WriteMessage() {
		super();
		// TODO Auto-generated constructor stub
	}

	public WriteMessage(WebDriver driver) {
		super();
		this.driver = driver;
	}
	
	public void writeMessage(){
		
		WebElement to = driver.findElement(By.xpath("//*/div[1]/div/div[3]/div[1]/div/div/div[2]/div/div/div"));
		to.click();
		to.sendKeys(EMAIL);

		WebElement popup = driver.findElement(By.xpath("//*/div[11]/div/div"));
		popup.click();

		WebElement topic = driver.findElement(By.xpath("//*/div[1]/div/div[3]/div[4]/div/div/div[2]/div/input"));
		topic.click();
		topic.sendKeys(TOPIC);

		WebElement frame = driver.findElement(By.xpath("//iframe[contains(@id,'composeEditor_ifr')]"));
		driver.switchTo().frame(frame);

		WebElement element = driver.findElement(By.id("tinymce"));
		element.sendKeys("Hi Svetlana.");
		element.sendKeys(" This letter is automatically generated by my selenium test.");
		element.sendKeys(" Please find my homework here https://github.com/igorkan45/Selenium2");
		element.sendKeys(" Have a nice day. Igor Kanunnikov");
		driver.switchTo().defaultContent();

		WebElement button = driver.findElement(By.xpath("//*/div[3]/div/div[2]/div[1]/div"));
		button.click();
	}

}
